lint:
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - .github/CONTRIBUTING.md
  multiqc_config: false
nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Luisa Santus, Jose Espinosa Carrasco
  description: Pipeline to run and benchmark multiple sequence alignment tools.
  force: false
  is_nfcore: true
  name: multiplesequencealign
  org: nf-core
  outdir: .
  version: 1.1.0dev
